### ISSUE TITLE
Invalid or corrupt jarfile copier.jar error when launching jar file.

### ISSUE THREAD

**Issue by Davis8988** [Antowka/copier#1]
Hello,  
I am trying to launch your application but getting an error :(  
trying to run: copier\out\artifacts\copier_jar\copier.jar 
getting the error: "Invalid or corrupt jarfile copier.jar".  

What can I do to solve it?
  
Thank you

**Comment by Antowka** [comment]
Hi! I didn't get the problem with it. But I updated jar file in bin/ folder.  Please try it again with new jar :)
